# Generated by Django 2.2.6 on 2021-01-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210116_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='posts.Post', verbose_name='post_id'),
        ),
    ]
