# Generated by Django 2.2.6 on 2021-01-22 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210122_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='post_id'),
        ),
    ]
