# Generated by Django 2.2.6 on 2021-01-26 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='follow_user',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='followed_user',
        ),
        migrations.AddField(
            model_name='relation',
            name='target_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_user', to=settings.AUTH_USER_MODEL, verbose_name='target_user'),
        ),
        migrations.AddField(
            model_name='relation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
